---
- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family | lower }}.yml"
    - default.yml

- name: Set apt to use https
  become: yes
  apt:
    name: apt-transport-https
    state: present

- name: Install system dependencies
  become: yes
  package:
    name: "{{ item }}"
    state: present
  register: result
  retries: 3
  until: result is succeeded
  with_items: "{{ system_dependencies }}"

- name: Install packages
  include: install-package.yml
  with_items: "{{ packages }}"
  when: packages | length > 0 and item.install | bool
