---
- name: Determine if terraform already installed
  stat:
    path: "{{ terraform_archive_path }}"
  register: terraform_installed

- name: Determine current terraform version
  block:
    - name: Get latest terraform version
      shell: "{{ terraform_archive_path }} --version | head -n1"
      register: current_terraform_version
      changed_when: False
      failed_when: False

    - debug:
        msg: "Currently installed terraform version: {{ current_terraform_version.stdout }}"
  when: terraform_installed.stat.exists

- name: Determine latest terraform version
  block:
    - name: Get latest version json
      uri:
        url: "{{ terraform_version_lookup_url }}"
        return_content: yes
        status_code: "200"
      register: terraform_version_json

    - name: Process latest version json
      set_fact:
        terraform_latest_version: >-
            {{ terraform_version_json.json | json_query('tag_name') | replace('v', '') }}

    - debug:
        msg: "Latest terraform version: {{ terraform_latest_version }}"
  when: terraform_version | lower == 'latest'
