---
- name: Determine if tflint already installed
  stat:
    path: "{{ tflint_archive_path }}"
  register: tflint_installed

- name: Determine current tflint version
  block:
    - name: Get latest tflint version
      shell: "{{ tflint_archive_path }} --version | head -n1"
      register: current_tflint_version
      changed_when: False
      failed_when: False

    - debug:
        msg: "Currently installed tflint version: {{ current_tflint_version.stdout }}"
  when: tflint_installed.stat.exists

- name: Determine latest tflint version
  block:
    - name: Get latest version json
      uri:
        url: "{{ tflint_version_lookup_url }}"
        return_content: yes
        status_code: "200"
      register: tflint_version_json

    - name: Process latest version json
      set_fact:
        tflint_latest_version: >-
            {{ tflint_version_json.json | json_query('tag_name') | replace('v', '') }}

    - debug:
        msg: "Latest tflint version: {{ tflint_latest_version }}"
  when: tflint_version | lower == 'latest'
