---
- name: Verify
  hosts: all

  vars:
    terraform_version: "0.12.18"
    tflint_version: "0.13.4"

  tasks:
    - name: "Verify terraform version: {{ terraform_version }} is installed"
      shell: terraform --version    # noqa 305
      register: terraform_version_command

    - assert:
        that: "terraform_version_command.rc == 0"
        fail_msg: "terraform is not installed"
        success_msg: "terraform is installed"

    - assert:
        that: "'0.12.18' in terraform_version_command.stdout"
        fail_msg: "terraform version: {{ terraform_version }} is not installed"
        success_msg: "terraform version: {{ terraform_version }} is installed"

    - name: "Verify tflint version: {{ tflint_version }} is installed"
      shell: tflint --version    # noqa 305
      register: tflint_version_command

    - assert:
        that: "tflint_version_command.rc == 0"
        fail_msg: "tflint is not installed"
        success_msg: "tflint is installed"

    - assert:
        that: "'0.13.4' in tflint_version_command.stdout"
        fail_msg: "tflint version: {{ tflint_version }} is not installed"
        success_msg: "tflint version: {{ tflint_version }} is installed"
